
# html lang
language: zh-CH

# main menu navigation
menu:
  首页: /
  关于: /about
  联系: /contact
  档案: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/chenstyle.css

# scripts loaded in the end of the body
scripts:
- /js/chenstyle.js
