
# html lang
language: zh-CH

# main menu navigation
menu:
  Home: /
  About: /about
  Contact: /contact
  Archives: /archives

# stylesheets loaded in the <head>
stylesheets:
- /css/chenstyle.css

# scripts loaded in the end of the body
scripts:
- /js/chenstyle.js
